server:
  port: 8083

# You MUST hit 127.0.0.1 instead of localhost

spring:
  security:
    oauth2:
      client:
        registration:
          drivers-client:
            client-id: drivers-id
            client-secret: drivers-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8083/login/oauth2/code/drivers-client
            scope:
              - openid
        provider:
          drivers-client:
            issuer-uri: http://auth-server:8081
