server:
  port: 8083

# You MUST hit 127.0.0.1 instead of localhost

spring:
  security:
    oauth2:
      client:
        registration:
          users-client-oidc:
            client-id: client-id
            client-secret: client-secret
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8083/login/oauth2/code/users-client-oidc
            scope:
              - openid
        provider:
          users-client-oidc:
            issuer-uri: http://auth-server:8081
